/** 插件公开状态，业务层可用它驱动自己的提交按钮和提示文案。 */
export const CAP_STATES = Object.freeze({
  IDLE: "idle",
  ATTESTING: "attesting",
  CHALLENGING: "challenging",
  SOLVING: "solving",
  REDEEMING: "redeeming",
  SUCCESS: "success",
  ERROR: "error",
  CANCELLED: "cancelled"
});

/** 当前插件协议只接受 Cap SHA-256 PoW，避免静默放过未知挑战。 */
export const CAP_PROTOCOL = Object.freeze({
  ALGORITHM: "sha256",
  DEFAULT_TIMEOUT_MS: 30000,
  MIN_TIMEOUT_MS: 1000,
  MAX_TIMEOUT_MS: 120000,
  MAX_CHALLENGE_COUNT: 512,
  MAX_SALT_LENGTH: 256,
  MAX_TARGET_LENGTH: 16
});

/** 稳定错误码用于宿主埋点；错误信息可安全展示给用户。 */
export const CAP_ERROR_CODES = Object.freeze({
  INVALID_REQUEST: "CAP_INVALID_REQUEST",
  INVALID_ADAPTER: "CAP_INVALID_ADAPTER",
  BUSY: "CAP_BUSY",
  TIMEOUT: "CAP_TIMEOUT",
  CANCELLED: "CAP_CANCELLED",
  UNSUPPORTED_PLATFORM: "CAP_UNSUPPORTED_PLATFORM",
  PLATFORM_ATTESTATION_FAILED: "CAP_PLATFORM_ATTESTATION_FAILED",
  CHALLENGE_FAILED: "CAP_CHALLENGE_FAILED",
  INVALID_CHALLENGE: "CAP_INVALID_CHALLENGE",
  UNSUPPORTED_CHALLENGE: "CAP_UNSUPPORTED_CHALLENGE",
  SOLVE_FAILED: "CAP_SOLVE_FAILED",
  REDEEM_FAILED: "CAP_REDEEM_FAILED",
  APP_BRIDGE_FAILED: "CAP_APP_BRIDGE_FAILED"
});
